version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: store-container
    environment:
      - POSTGRES_USER=Ilya
      - POSTGRES_PASSWORD=8977@X
      - POSTGRES_DB=storeDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: