spring.application.name=Store

spring.datasource.url=jdbc:postgresql://localhost:5432/storeDB
spring.datasource.username=Ilya
spring.datasource.password=8977@X

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true